"use strict";
const $=x=>document.getElementById(x),audio=$("audio"),cv=$("canvas"),c=cv.getContext("2d");
let cues=[],sel=-1,url=null,raf=0,stop=false,ctxA,src,dst,last;
const base=[["none","Neutral"],["triangle","Triangel"],["sides","Tre sidor"],["corners","Tre hörn"],["angles","Tre vinklar"],["sum180","180°"],["perimeter","a+b+c"],["base","b"],["height","h"],["areaFill","Fyll area"],["area","A=(b×h)÷2"],["pulse","Pulser"],["bars","Musikstaplar"],["question","Frågetecken"],["numbers","6–9"],["countdown","3–2–1"],["confetti","Konfetti"],["steps","Steg"]],mul=[];
for(let a=6;a<10;a++)for(let b=6;b<10;b++)mul.push([`m-${a}-${b}-q`,`${a} × ${b} = ?`],[`m-${a}-${b}-a`,`${a} × ${b} = ${a*b}`]);
const scenes=[...base,...mul];
function st(s,p){$("status").textContent=s;if(p!=null)$("bar").style.width=Math.max(0,Math.min(100,p))+"%"}
function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}
function num(v){return Number.isFinite(v)?v:null}
function save(){localStorage.setItem("mmm",JSON.stringify({name:$("projectName").value,lyrics:$("lyrics").value,cues,ratio:"16:9",quality:$("quality").value,exportMode:$("exportMode").value}))}
function apply(p){$("projectName").value=p.name||"Math Movie";$("lyrics").value=p.lyrics||"";cues=(p.cues||[]).map(x=>({...x,start:num(+x.start),end:num(+x.end),scene:x.scene||guess(x.text||"")}));$("quality").value=p.quality||"720";$("exportMode").value=p.exportMode||"smooth";rows();draw(0)}
function guess(t){let x=t.toLowerCase(),m=x.match(/([6-9]).*?([6-9])/);if(m)return`m-${m[1]}-${m[2]}-${(/\?|\.\.\.$/.test(x)?"q":"a")}`;if(x.includes("180"))return"sum180";if(/omkrets|perimeter|périmètre|perímetro/.test(x))return"perimeter";if(/area|aire|área/.test(x))return"area";if(/höjd|height|hauteur|altura/.test(x))return"height";if(/bas|base/.test(x))return"base";if(/hörn|corner|sommet|vértice/.test(x))return"corners";if(/vinkel|angle|ángulo/.test(x))return"angles";if(/sida|side|côté|lado/.test(x))return"sides";if(/tänk|think|pense|piensa/.test(x))return"question";if(/sex till nio|six to nine|six à neuf|seis a nueve/.test(x))return"numbers";return"pulse"}
function select(i,seek=true){sel=i;if(seek&&Number.isFinite(cues[i]?.start))audio.currentTime=cues[i].start;rows(false);timeline();draw(audio.currentTime)}
function place(i){let q=cues[i],start=audio.currentTime||0,len=Number.isFinite(q.end)&&Number.isFinite(q.start)?Math.max(.25,q.end-q.start):2.5;q.start=start;q.end=start+len;select(i,false);save()}
function shift(i,d){let q=cues[i];if(!Number.isFinite(q.start))return place(i);let len=Math.max(.05,q.end-q.start);q.start=Math.max(0,q.start+d);q.end=q.start+len;select(i,false);save()}
function setDuration(i,v){let q=cues[i],len=Math.max(.05,+v||.05);if(!Number.isFinite(q.start))q.start=audio.currentTime||0;q.end=q.start+len;select(i,false);save()}
function rows(redraw=true){let b=$("timingList");b.innerHTML="";cues.forEach((q,i)=>{let r=document.createElement("div"),duration=Number.isFinite(q.start)&&Number.isFinite(q.end)?Math.max(.05,q.end-q.start):2.5;r.className="timing-row"+(i===sel?" selected":"");r.innerHTML=`<div class="row-title"><div class="row-number">${i+1}</div><input data-k="text" value="${esc(q.text)}"></div><div class="time-grid"><div><label>Start</label><input data-k="start" type="number" step=".01" value="${Number.isFinite(q.start)?q.start.toFixed(2):""}"></div><div><label>Slut</label><input data-k="end" type="number" step=".01" value="${Number.isFinite(q.end)?q.end.toFixed(2):""}"></div><div><label>Längd</label><input data-k="duration" type="number" step=".05" min=".05" value="${duration.toFixed(2)}"></div></div><div class="scene-wrap"><label>Animation</label><select class="scene">${scenes.map(s=>`<option value="${s[0]}" ${s[0]===q.scene?"selected":""}>${s[1]}</option>`).join("")}</select></div><div class="row-actions"><button class="place-btn">Placera vid spelhuvud</button><button data-move="-.25">← 0,25 s</button><button data-move=".25">0,25 s →</button></div>`;
r.onclick=e=>{if(!e.target.closest("input,select,button"))select(i)};
r.querySelector('[data-k="text"]').onchange=e=>{q.text=e.target.value;save();timeline();draw(audio.currentTime)};
r.querySelector('[data-k="start"]').onchange=e=>{q.start=e.target.value===""?null:+e.target.value;if(Number.isFinite(q.start)&&(!Number.isFinite(q.end)||q.end<=q.start))q.end=q.start+duration;save();rows()};
r.querySelector('[data-k="end"]').onchange=e=>{q.end=e.target.value===""?null:+e.target.value;if(Number.isFinite(q.end)&&Number.isFinite(q.start)&&q.end<=q.start)q.end=q.start+.05;save();rows()};
r.querySelector('[data-k="duration"]').onchange=e=>setDuration(i,e.target.value);
r.querySelector(".scene").onchange=e=>{q.scene=e.target.value;sel=i;save();timeline();draw(audio.currentTime)};
r.querySelector(".place-btn").onclick=()=>place(i);r.querySelectorAll("[data-move]").forEach(x=>x.onclick=()=>shift(i,+x.dataset.move));b.appendChild(r)});if(redraw)timeline()}
$("saveLocal").onclick=()=>{save();st("Projekt sparat.")};
$("downloadProject").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([localStorage.getItem("mmm")||"{}"],{type:"application/json"}));a.download="math-movie.json";a.click()};
$("openProject").onclick=()=>$("projectFile").click();
$("projectFile").onchange=async e=>{try{apply(JSON.parse(await e.target.files[0].text()));save()}catch(x){alert("Projektet kunde inte öppnas.")}};
$("makeRows").onclick=()=>{let a=$("lyrics").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!a.length)return alert("Lägg in text.");let d=audio.duration||Math.max(30,a.length*3),step=d/a.length;cues=a.map((text,i)=>({text,start:i*step,end:(i+1)*step,scene:guess(text)}));sel=0;rows();save()};
$("markTime").onclick=()=>{let i=cues.findIndex(x=>!Number.isFinite(x.start));if(i<0)i=Math.max(0,sel);place(i)};
$("resetTimes").onclick=()=>{cues.forEach(x=>{x.start=null;x.end=null});rows();save()};
$("audioFile").onclick=e=>e.target.value="";
$("audioFile").onchange=e=>{let f=e.target.files[0];if(!f)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);audio.src=url;audio.load();audio.onloadedmetadata=()=>{st(`Ljud laddat: ${f.name}`);timeline()};audio.onerror=()=>st("Ljudfilen kunde inte läsas.")};
function dur(){return Math.max(audio.duration||0,...cues.map(x=>Number.isFinite(x.end)?x.end:0),20)}
function pps(){return +$("timelineZoom").value||70}
function assignLanes(){let timed=cues.map((q,i)=>({q,i})).filter(x=>Number.isFinite(x.q.start)&&Number.isFinite(x.q.end)).sort((a,b)=>a.q.start-b.q.start),ends=[];for(const x of timed){let lane=ends.findIndex(v=>v<=x.q.start+.01);if(lane<0)lane=ends.length;ends[lane]=x.q.end;x.lane=lane}return timed}
function timeline(){let p=pps(),timed=assignLanes(),lanes=Math.max(1,...timed.map(x=>x.lane+1)),h=Math.min(244,30+lanes*52);$("timeline").style.height=h+"px";let w=Math.max($("timelineShell").clientWidth,dur()*p);$("timeline").style.width=w+"px";$("zoomValue").textContent=Math.round(p);let r=$("ruler");r.innerHTML="";for(let s=0;s<=dur();s+=(p>=120?1:p>=65?2:5)){let t=document.createElement("div");t.className="tick";t.style.left=s*p+"px";t.textContent=s+"s";r.appendChild(t)}let tr=$("track");tr.innerHTML="";for(let l=1;l<lanes;l++){let line=document.createElement("div");line.className="lane-line";line.style.top=l*52+"px";tr.appendChild(line)}for(const {q,i,lane} of timed){let el=document.createElement("div");el.className="cue-block"+(i===sel?" selected":"");el.style.left=q.start*p+"px";el.style.width=Math.max(36,(q.end-q.start)*p)+"px";el.style.top=(5+lane*52)+"px";el.innerHTML=`<i class="handle left"></i><span class="cue-label">${esc(q.text)}</span><i class="handle right"></i>`;el.onpointerdown=e=>dragCue(e,el,i);tr.appendChild(el)}head()}
function dragCue(e,el,i){e.preventDefault();e.stopPropagation();sel=i;let p=pps(),x=e.clientX,a=cues[i].start,b=cues[i].end,m=e.target.classList.contains("left")?"l":e.target.classList.contains("right")?"r":"m";el.setPointerCapture(e.pointerId);el.onpointermove=v=>{let d=(v.clientX-x)/p;if(m==="m"){let len=b-a,ns=Math.max(0,a+d);cues[i].start=ns;cues[i].end=ns+len}else if(m==="l")cues[i].start=Math.max(0,Math.min(b-.05,a+d));else cues[i].end=Math.max(a+.05,b+d);timeline();draw(audio.currentTime)};el.onpointerup=()=>{el.onpointermove=null;save();rows()}}
function head(){$("playhead").style.left=audio.currentTime*pps()+"px"}
$("timeline").onclick=e=>{if(e.target.closest(".cue-block"))return;audio.currentTime=Math.max(0,(e.clientX-$("timeline").getBoundingClientRect().left)/pps());head();draw(audio.currentTime)};
$("timelineZoom").oninput=timeline;$("fitTimeline").onclick=()=>{$("timelineZoom").value=Math.max(35,Math.min(180,$("timelineShell").clientWidth/dur()));timeline()};
document.querySelectorAll("[data-nudge]").forEach(b=>b.onclick=()=>{if(sel<0)return;shift(sel,+b.dataset.nudge)});
document.querySelectorAll("[data-edge]").forEach(b=>b.onclick=()=>{if(sel<0)return;let q=cues[sel];if(b.dataset.edge==="start"){q.start=Math.min(audio.currentTime,(q.end||audio.currentTime+.1)-.05)}else q.end=Math.max(audio.currentTime,(q.start||0)+.05);rows();save()});
audio.ontimeupdate=()=>{head();draw(audio.currentTime)};window.onresize=timeline;
function size(){let q=+$("quality").value;cv.width=Math.round(q*16/9);cv.height=q}
function tc(s,y,z,col="#fff"){c.fillStyle=col;c.font=`900 ${z}px system-ui`;c.textAlign="center";c.fillText(s,cv.width/2,y)}
function cue(t){return cues.find(x=>Number.isFinite(x.start)&&Number.isFinite(x.end)&&t>=x.start&&t<x.end)}
function draw(t){let w=cv.width,h=cv.height,g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,"#081229");g.addColorStop(1,"#172554");c.fillStyle=g;c.fillRect(0,0,w,h);let q=cue(t),s=q?.scene||"none",p=q?Math.max(0,Math.min(1,(t-q.start)/(q.end-q.start))):0,m=/^m-(\d)-(\d)-(q|a)$/.exec(s);if(m)tc(m[3]==="a"?`${m[1]} × ${m[2]} = ${+m[1]*+m[2]}`:`${m[1]} × ${m[2]} = ?`,h*.48,w/(m[3]==="a"?11:10),m[3]==="a"?"#22c55e":"#facc15");else if(s==="sum180")tc("180°",h*.48,w/6,"#facc15");else if(s==="perimeter")tc("a + b + c",h*.48,w/10);else if(s==="area")tc("A = (b × h) ÷ 2",h*.48,w/14);else if(s==="question")tc("?",h*.48,w/5,"#facc15");else if(s==="numbers")tc("6   7   8   9",h*.48,w/13);else if(s==="countdown")tc(String(Math.max(1,3-Math.floor(p*3))),h*.48,w/5,"#facc15");else if(s==="bars"){for(let i=0;i<12;i++){let bh=h*(.05+.25*Math.abs(Math.sin(p*8+i)));c.fillStyle=i%2?"#38bdf8":"#22c55e";c.fillRect(w*(.18+i*.055),h*.58-bh,w*.03,bh)}}else{let A=[w*.5,h*.16],B=[w*.2,h*.68],D=[w*.8,h*.68];c.strokeStyle="#fff";c.lineWidth=Math.max(6,w/100);c.beginPath();c.moveTo(...A);c.lineTo(...B);c.lineTo(...D);c.closePath();c.stroke();if(s==="corners"){[A,B,D].forEach(v=>{c.fillStyle="#facc15";c.beginPath();c.arc(v[0],v[1],w*.03,0,7);c.fill()})}}if(q){c.fillStyle="rgba(2,6,23,.9)";c.fillRect(0,h*.82,w,h*.18);tc(q.text,h*.91,Math.max(28,w/25))}}
function valid(){return cues.length&&cues.every(x=>Number.isFinite(x.start)&&Number.isFinite(x.end)&&x.end>x.start)}
$("previewBtn").onclick=()=>{if(!audio.src)return alert("Välj ljudfil.");if(!valid())return alert("Placera alla textklipp.");size();audio.play();cancelAnimationFrame(raf);let loop=()=>{draw(audio.currentTime);head();if(!audio.paused&&!audio.ended)raf=requestAnimationFrame(loop)};loop()};
$("stopBtn").onclick=()=>{stop=true;audio.pause();cancelAnimationFrame(raf)};
function adst(){if(!ctxA){ctxA=new(window.AudioContext||window.webkitAudioContext)();src=ctxA.createMediaElementSource(audio);dst=ctxA.createMediaStreamDestination();src.connect(dst);src.connect(ctxA.destination)}return dst}
$("renderBtn").onclick=async()=>{if(!audio.src||!valid())return alert("Ladda ljud och placera alla textklipp.");size();stop=false;audio.pause();audio.currentTime=0;try{let v=cv.captureStream(25),d=adst();if(ctxA.state==="suspended")await ctxA.resume();let stream=new MediaStream([...v.getVideoTracks(),...d.stream.getAudioTracks()]),type=["video/mp4","video/webm"].find(x=>MediaRecorder.isTypeSupported(x))||"",rec=new MediaRecorder(stream,type?{mimeType:type}:undefined),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);let done=new Promise((r,j)=>{rec.onstop=r;rec.onerror=j});rec.start(1000);await audio.play();let tick=()=>{draw(audio.currentTime);st(`Skapar video… ${Math.round(audio.currentTime)} / ${Math.round(audio.duration)} s`,audio.currentTime/audio.duration*100);if(!audio.ended&&!stop)setTimeout(tick,40);else rec.stop()};tick();await done;let blob=new Blob(chunks,{type:type||"video/webm"}),a=$("download");if(last)URL.revokeObjectURL(last);last=URL.createObjectURL(blob);a.href=last;a.download="math-movie."+(type.includes("mp4")?"mp4":"webm");a.style.display="block";st("Videon är klar.",100)}catch(e){st("Fel: "+e.message)}};
["projectName","lyrics","quality","exportMode"].forEach(id=>$(id).onchange=save);
try{let p=localStorage.getItem("mmm");if(p)apply(JSON.parse(p));else{draw(0);timeline()}}catch(e){draw(0);timeline()}